from zmlx.ui.widget.about import About
from zmlx.ui.widget.app_path_edit import AppPathEdit
from zmlx.ui.widget.code_edit import CodeEdit
from zmlx.ui.widget.code_history_view import CodeHistoryView
from zmlx.ui.widget.console_state_label import ConsoleStateLabel
from zmlx.ui.widget.cwd_view import CwdView
from zmlx.ui.widget.demo_view import DemoView
from zmlx.ui.widget.env_edit import EnvEdit
from zmlx.ui.widget.feedback_tool import FeedbackTool
from zmlx.ui.widget.fn2 import *
from zmlx.ui.widget.img import ImageView
from zmlx.ui.widget.label import Label
from zmlx.ui.widget.mem_view import MemView
from zmlx.ui.widget.output_history_view import OutputHistoryView
from zmlx.ui.widget.output_widget import OutputWidget
from zmlx.ui.widget.plt import MatplotWidget
from zmlx.ui.widget.readme_browser import ReadMeBrowser
from zmlx.ui.widget.reg_tool import RegTool
from zmlx.ui.widget.setup_file_edit import SetupFileEdit
from zmlx.ui.widget.tab_detail_view import TabDetailView
from zmlx.ui.widget.tab_widget import TabWidget
from zmlx.ui.widget.text_browser import TextBrowser
from zmlx.ui.widget.text_file_edit import TextFileEdit
from zmlx.ui.widget.timer_view import TimerView
